name: Publish Container Images to GHCR

on:
  push:
    branches:
      - main

jobs:
  container-image-build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Release package
        run: |
          docker buildx build $ARGS \
            --build-arg CONTEXT_PATH="containers/$container" \
            --platform linux/amd64,linux/arm64 \
            --tag ghcr.io/denoland/${container}:${tag} \
            --tag ghcr.io/denoland/${container}:latest \
            --push \
            ./containers/$container

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          context: ./
          platforms: |
            linux/amd64
          tags: |
            ghcr.io/igorbdl/gha-arc-runner:latest
          build-args: |
            RUNNER_VERSION=igorbdl-v0.1
          push: true
          labels: |
            org.opencontainers.image.source=${{github.server_url}}/${{github.repository}}
            org.opencontainers.image.description=${{github.server_url}}/${{github.repository}}

